version: '3.8'

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    ports:
      - "8081:8081"
    volumes:
      - ./config/o11y:/home/dochkas/o11y-examples/config/o11y
    environment:
      USER_MANAGER_HOST: user-manager:50051
    depends_on:
      - user-manager
  user-manager:
    build:
      context: .
      dockerfile: Dockerfile.user
    volumes:
      - ./config/o11y:/home/dochkas/o11y-examples/config/o11y
  otel-collector:
    image: otel/opentelemetry-collector:0.108.0
    volumes:
      - ./config/o11y/collector-config.yaml:/etc/otelcol/config.yaml