apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gateway.serviceName }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.gateway.appName }}
  ports:
  - port: 80
    targetPort: http
    name: http
    nodePort: 30050