apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.userManager.serviceName }}
spec:
  selector:
    app: {{ .Values.userManager.appName }}
  ports:
  - port: {{ .Values.userManager.port }}
    targetPort: grpc
    name: grpc
